# Generated by Django 5.0.7 on 2024-08-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('battery_life', models.CharField(max_length=255)),
                ('operating_system', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('dimensions', models.CharField(max_length=255)),
                ('connectivity', models.CharField(max_length=255)),
                ('features', models.TextField()),
                ('reviews', models.TextField()),
                ('availability', models.BooleanField()),
                ('sku', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('manufacturer_part_number', models.CharField(max_length=255)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.specification')),
            ],
        ),
    ]
